sudo: false
language: python

matrix:
    include:
        - { python: 2.7, env: py27-dj1.9-test }
        - { python: 2.7, env: py27-dj1.10-test }
        - { python: 2.7, env: py27-dj1.11-test }
        - { python: 3.4, env: py34-dj1.9-test }
        - { python: 3.4, env: py34-dj1.10-test }
        - { python: 3.4, env: py34-dj1.11-test }
        - { python: 3.4, env: py34-djmaster-test }
        - { python: 2.7, env: py27-flake }
        - { python: 3.4, env: py34-flake }
    allow_failures:
        - env: py27-dj1.11-test
        - env: py34-dj1.11-test
        - env: py34-djmaster-test

install:
    - pip install tox>=2.5.0

script:
- tox
